# Generated by Django 5.2.5 on 2025-08-31 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('date_receipt', models.DateField()),
                ('appellant_name', models.CharField(max_length=100)),
                ('respondent_name', models.CharField(max_length=100)),
                ('subject', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
